# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      proto_generator:protoBuilder:
        options:
          useWellKnownTypes: true
          useProtoFieldNamingConventions: true
          packageName: com.mycompany.myproject
          wellKnownDurationType: $Duration
          wellKnownTimestampType: $Timestamp
          defaultIntPrecision: int32
          options:
            - go_package = "./stubs"
