name: squarealfa_security
description: Package containing security-related features, like JWT token handling and password hashing.
repository: https://gitlab.com/dartaculous/dartaculous
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/security/squarealfa_security
version: 3.0.1


environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  crypto: ^3.0.0
  cryptography: ^2.0.1
  jose: ^0.3.2
  http: ^0.13.3

dev_dependencies:
  test: ^1.17.11
  lints: ^2.0.0
  