name: sqfsync
description: Adapter for dbsync that uses sqlite database.
repository: https://gitlab.com/dartaculous/dartaculous
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/dbsync/sqfsync
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sqflite_common: ^2.4.1
  dbsync: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
