// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: list_database_request.proto

package stubs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListDatabasesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnectionOid []byte                        `protobuf:"bytes,1,opt,name=connectionOid,proto3" json:"connectionOid,omitempty"`
	Request       *ListDatabasesRequest_Request `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *ListDatabasesRequest) Reset() {
	*x = ListDatabasesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_list_database_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDatabasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesRequest) ProtoMessage() {}

func (x *ListDatabasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_list_database_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesRequest.ProtoReflect.Descriptor instead.
func (*ListDatabasesRequest) Descriptor() ([]byte, []int) {
	return file_list_database_request_proto_rawDescGZIP(), []int{0}
}

func (x *ListDatabasesRequest) GetConnectionOid() []byte {
	if x != nil {
		return x.ConnectionOid
	}
	return nil
}

func (x *ListDatabasesRequest) GetRequest() *ListDatabasesRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type ListDatabasesRequest_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter              []byte                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	NameOnly            *wrapperspb.BoolValue `protobuf:"bytes,2,opt,name=nameOnly,proto3" json:"nameOnly,omitempty"`
	AuthorizedDatabases *wrapperspb.BoolValue `protobuf:"bytes,3,opt,name=authorizedDatabases,proto3" json:"authorizedDatabases,omitempty"`
}

func (x *ListDatabasesRequest_Request) Reset() {
	*x = ListDatabasesRequest_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_list_database_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDatabasesRequest_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesRequest_Request) ProtoMessage() {}

func (x *ListDatabasesRequest_Request) ProtoReflect() protoreflect.Message {
	mi := &file_list_database_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesRequest_Request.ProtoReflect.Descriptor instead.
func (*ListDatabasesRequest_Request) Descriptor() ([]byte, []int) {
	return file_list_database_request_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ListDatabasesRequest_Request) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListDatabasesRequest_Request) GetNameOnly() *wrapperspb.BoolValue {
	if x != nil {
		return x.NameOnly
	}
	return nil
}

func (x *ListDatabasesRequest_Request) GetAuthorizedDatabases() *wrapperspb.BoolValue {
	if x != nil {
		return x.AuthorizedDatabases
	}
	return nil
}

var File_list_database_request_proto protoreflect.FileDescriptor

var file_list_database_request_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x02,
	0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0xa7, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x08, 0x6e, 0x61, 0x6d,
	0x65, 0x4f, 0x6e, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f,
	0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08, 0x6e, 0x61, 0x6d, 0x65, 0x4f, 0x6e, 0x6c,
	0x79, 0x12, 0x4c, 0x0a, 0x13, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x44,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x13, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x73, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x73, 0x74, 0x75, 0x62, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_list_database_request_proto_rawDescOnce sync.Once
	file_list_database_request_proto_rawDescData = file_list_database_request_proto_rawDesc
)

func file_list_database_request_proto_rawDescGZIP() []byte {
	file_list_database_request_proto_rawDescOnce.Do(func() {
		file_list_database_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_list_database_request_proto_rawDescData)
	})
	return file_list_database_request_proto_rawDescData
}

var file_list_database_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_list_database_request_proto_goTypes = []interface{}{
	(*ListDatabasesRequest)(nil),         // 0: ListDatabasesRequest
	(*ListDatabasesRequest_Request)(nil), // 1: ListDatabasesRequest.Request
	(*wrapperspb.BoolValue)(nil),         // 2: google.protobuf.BoolValue
}
var file_list_database_request_proto_depIdxs = []int32{
	1, // 0: ListDatabasesRequest.request:type_name -> ListDatabasesRequest.Request
	2, // 1: ListDatabasesRequest.Request.nameOnly:type_name -> google.protobuf.BoolValue
	2, // 2: ListDatabasesRequest.Request.authorizedDatabases:type_name -> google.protobuf.BoolValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_list_database_request_proto_init() }
func file_list_database_request_proto_init() {
	if File_list_database_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_list_database_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDatabasesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_list_database_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDatabasesRequest_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_list_database_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_list_database_request_proto_goTypes,
		DependencyIndexes: file_list_database_request_proto_depIdxs,
		MessageInfos:      file_list_database_request_proto_msgTypes,
	}.Build()
	File_list_database_request_proto = out.File
	file_list_database_request_proto_rawDesc = nil
	file_list_database_request_proto_goTypes = nil
	file_list_database_request_proto_depIdxs = nil
}
