name: csharp_generator_example
description: csharp_annotations and csharp_generator packages demonstration project
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/proto_mapper/example
repository: https://gitlab.com/dartaculous/dartaculous
version: 2.0.0

publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  protobuf: ^2.1.0
  csharp_annotations: ^0.0.1-dev.0
  decimal: ^2.0.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.14.4
  csharp_generator: ^0.0.1-dev.1
  build_runner: ^2.1.2

