name: dart_framework
repository: https://gitlab.com/ruicraveiro/dart_framework

packages:
  - nosql_repository/**
  - arango_driver/**
  - arango_repository/**
  - common_types/**
  - generators_common/**
  - security/**
  - proto_mapper/**
  - map_mapper/**
  - defaults_provider/**
  - entity/**
  - example_model/**
  - grpc_host/**

ignore:
  - map_mapper/test_mongo/*
  - defaults_provider/example/*

scripts:
  analyze: melos exec -- "dart analyze ."

  test: 
    melos exec --dir-exists="test" --ignore="*firebase*admin*" --ignore="*mongo*" --ignore="*arango*" -- "dart test"
