name: dart_framework
repository: https://gitlab.com/ruicraveiro/dart_framework

ide:
  intellij:
    enabled: false


packages:
  - nosql_repository/**
  - arango_driver/package/**
  - generators_common/**
  - security/**
  - proto_mapper/**
  - map_mapper/**
  - entity/**
  - grpc_host/**
  - go_bridge/**
  - mongo_go/**
  - firebase_go_admin/**
  - dbsync/**
  - csharp_mapper/**


