name: dart_framework
repository: https://gitlab.com/ruicraveiro/dart_framework

packages:
  - nosql_repository/**
  - arango_driver/package/**
  - arango_repository/package/**
  - mongo_repository/package/**
  - common_types/**
  - generators_common/**
  - security/**
  - proto_mapper/**
  - map_mapper/**
  - defaults_provider/**
  - entity/**
  - entity_adapter/**
  - example_model/**
  - grpc_host/**
  - go_bridge/**

ignore:
  - map_mapper/test_mongo/*
  - defaults_provider/example/*
  - entity_adapter/example/*

scripts:
  analyze: melos exec -- "dart analyze ." 

  gen:
    run: melos exec --dir-exists="test" --ignore="*firebase*admin*" --ignore="*mongo*" --ignore="*arango*" --file-exists="gen.sh" -- "./gen.sh"

  test:
    run: melos exec --dir-exists="test" --ignore="*firebase*admin*" --ignore="*mongo*" --ignore="*arango*" -- "dart test"
