name: dart_framework
repository: https://gitlab.com/ruicraveiro/dart_framework

packages:
  - nosql_repository/**
  - arango_driver/package/**
  - arango_repository/package/**
  - common_types/**
  - generators_common/**
  - security/**
  - proto_mapper/**
  - map_mapper/**
  - defaults_provider/**
  - entity/**
  - entity_adapter/**
  - example_model/**
  - grpc_host/**
  - go_bridge/**
  - mongo_go/**
  - firebase_go_admin/**

ignore:
  - arango_driver/test/**
  - arango_repository/test/**
  - map_mapper/test/**
  - defaults_provider/example/*
  - entity_adapter/example/*

scripts:
  analyze: melos exec -- "dart analyze ."

  gen:
    run: melos exec --dir-exists="test" --ignore="*firebase*admin*" --ignore="*mongo*" --file-exists="gen.sh" -- "./gen.sh"

  make:
    run: echo "Making"

  test:
    run: 
      make test && melos exec --dir-exists="test" --ignore="*firebase*admin*" --ignore="*mongo*" --ignore="*arango*" --ignore="*firebase_go_admin*" -- "dart test" 
