// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: bulk_write.proto

package mongo_stubs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BulkWriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CollectionOid []byte        `protobuf:"bytes,1,opt,name=collectionOid,proto3" json:"collectionOid,omitempty"`
	SessionOid    []byte        `protobuf:"bytes,2,opt,name=sessionOid,proto3" json:"sessionOid,omitempty"`
	WriteModels   []*WriteModel `protobuf:"bytes,3,rep,name=writeModels,proto3" json:"writeModels,omitempty"`
	// Types that are assignable to Opts:
	//
	//	*BulkWriteRequest_Options
	Opts isBulkWriteRequest_Opts `protobuf_oneof:"opts"`
}

func (x *BulkWriteRequest) Reset() {
	*x = BulkWriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bulk_write_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkWriteRequest) ProtoMessage() {}

func (x *BulkWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_write_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkWriteRequest.ProtoReflect.Descriptor instead.
func (*BulkWriteRequest) Descriptor() ([]byte, []int) {
	return file_bulk_write_proto_rawDescGZIP(), []int{0}
}

func (x *BulkWriteRequest) GetCollectionOid() []byte {
	if x != nil {
		return x.CollectionOid
	}
	return nil
}

func (x *BulkWriteRequest) GetSessionOid() []byte {
	if x != nil {
		return x.SessionOid
	}
	return nil
}

func (x *BulkWriteRequest) GetWriteModels() []*WriteModel {
	if x != nil {
		return x.WriteModels
	}
	return nil
}

func (m *BulkWriteRequest) GetOpts() isBulkWriteRequest_Opts {
	if m != nil {
		return m.Opts
	}
	return nil
}

func (x *BulkWriteRequest) GetOptions() *BulkWriteOptions {
	if x, ok := x.GetOpts().(*BulkWriteRequest_Options); ok {
		return x.Options
	}
	return nil
}

type isBulkWriteRequest_Opts interface {
	isBulkWriteRequest_Opts()
}

type BulkWriteRequest_Options struct {
	Options *BulkWriteOptions `protobuf:"bytes,5,opt,name=options,proto3,oneof"`
}

func (*BulkWriteRequest_Options) isBulkWriteRequest_Opts() {}

type BulkWriteOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BypassDocumentValidation *wrapperspb.BoolValue `protobuf:"bytes,1,opt,name=bypass_document_validation,json=bypassDocumentValidation,proto3" json:"bypass_document_validation,omitempty"`
	Comment                  []byte                `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Ordered                  *wrapperspb.BoolValue `protobuf:"bytes,3,opt,name=ordered,proto3" json:"ordered,omitempty"`
	Let                      []byte                `protobuf:"bytes,4,opt,name=let,proto3" json:"let,omitempty"`
}

func (x *BulkWriteOptions) Reset() {
	*x = BulkWriteOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bulk_write_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkWriteOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkWriteOptions) ProtoMessage() {}

func (x *BulkWriteOptions) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_write_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkWriteOptions.ProtoReflect.Descriptor instead.
func (*BulkWriteOptions) Descriptor() ([]byte, []int) {
	return file_bulk_write_proto_rawDescGZIP(), []int{1}
}

func (x *BulkWriteOptions) GetBypassDocumentValidation() *wrapperspb.BoolValue {
	if x != nil {
		return x.BypassDocumentValidation
	}
	return nil
}

func (x *BulkWriteOptions) GetComment() []byte {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *BulkWriteOptions) GetOrdered() *wrapperspb.BoolValue {
	if x != nil {
		return x.Ordered
	}
	return nil
}

func (x *BulkWriteOptions) GetLet() []byte {
	if x != nil {
		return x.Let
	}
	return nil
}

type WriteModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Ops:
	//
	//	*WriteModel_InsertOneModel
	//	*WriteModel_DeleteOneModel
	//	*WriteModel_ReplaceOneModel
	//	*WriteModel_UpdateOneModel
	//	*WriteModel_DeleteManyModel
	//	*WriteModel_UpdateManyModel
	Ops isWriteModel_Ops `protobuf_oneof:"ops"`
}

func (x *WriteModel) Reset() {
	*x = WriteModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bulk_write_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteModel) ProtoMessage() {}

func (x *WriteModel) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_write_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteModel.ProtoReflect.Descriptor instead.
func (*WriteModel) Descriptor() ([]byte, []int) {
	return file_bulk_write_proto_rawDescGZIP(), []int{2}
}

func (m *WriteModel) GetOps() isWriteModel_Ops {
	if m != nil {
		return m.Ops
	}
	return nil
}

func (x *WriteModel) GetInsertOneModel() *InsertOneModel {
	if x, ok := x.GetOps().(*WriteModel_InsertOneModel); ok {
		return x.InsertOneModel
	}
	return nil
}

func (x *WriteModel) GetDeleteOneModel() *DeleteOneModel {
	if x, ok := x.GetOps().(*WriteModel_DeleteOneModel); ok {
		return x.DeleteOneModel
	}
	return nil
}

func (x *WriteModel) GetReplaceOneModel() *ReplaceOneModel {
	if x, ok := x.GetOps().(*WriteModel_ReplaceOneModel); ok {
		return x.ReplaceOneModel
	}
	return nil
}

func (x *WriteModel) GetUpdateOneModel() *UpdateOneModel {
	if x, ok := x.GetOps().(*WriteModel_UpdateOneModel); ok {
		return x.UpdateOneModel
	}
	return nil
}

func (x *WriteModel) GetDeleteManyModel() *DeleteManyModel {
	if x, ok := x.GetOps().(*WriteModel_DeleteManyModel); ok {
		return x.DeleteManyModel
	}
	return nil
}

func (x *WriteModel) GetUpdateManyModel() *UpdateManyModel {
	if x, ok := x.GetOps().(*WriteModel_UpdateManyModel); ok {
		return x.UpdateManyModel
	}
	return nil
}

type isWriteModel_Ops interface {
	isWriteModel_Ops()
}

type WriteModel_InsertOneModel struct {
	InsertOneModel *InsertOneModel `protobuf:"bytes,1,opt,name=insertOneModel,proto3,oneof"`
}

type WriteModel_DeleteOneModel struct {
	DeleteOneModel *DeleteOneModel `protobuf:"bytes,2,opt,name=deleteOneModel,proto3,oneof"`
}

type WriteModel_ReplaceOneModel struct {
	ReplaceOneModel *ReplaceOneModel `protobuf:"bytes,3,opt,name=replaceOneModel,proto3,oneof"`
}

type WriteModel_UpdateOneModel struct {
	UpdateOneModel *UpdateOneModel `protobuf:"bytes,4,opt,name=updateOneModel,proto3,oneof"`
}

type WriteModel_DeleteManyModel struct {
	DeleteManyModel *DeleteManyModel `protobuf:"bytes,5,opt,name=deleteManyModel,proto3,oneof"`
}

type WriteModel_UpdateManyModel struct {
	UpdateManyModel *UpdateManyModel `protobuf:"bytes,6,opt,name=updateManyModel,proto3,oneof"`
}

func (*WriteModel_InsertOneModel) isWriteModel_Ops() {}

func (*WriteModel_DeleteOneModel) isWriteModel_Ops() {}

func (*WriteModel_ReplaceOneModel) isWriteModel_Ops() {}

func (*WriteModel_UpdateOneModel) isWriteModel_Ops() {}

func (*WriteModel_DeleteManyModel) isWriteModel_Ops() {}

func (*WriteModel_UpdateManyModel) isWriteModel_Ops() {}

type InsertOneModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Document []byte `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
}

func (x *InsertOneModel) Reset() {
	*x = InsertOneModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bulk_write_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertOneModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertOneModel) ProtoMessage() {}

func (x *InsertOneModel) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_write_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertOneModel.ProtoReflect.Descriptor instead.
func (*InsertOneModel) Descriptor() ([]byte, []int) {
	return file_bulk_write_proto_rawDescGZIP(), []int{3}
}

func (x *InsertOneModel) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

type DeleteOneModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter []byte `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Hint   []byte `protobuf:"bytes,2,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *DeleteOneModel) Reset() {
	*x = DeleteOneModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bulk_write_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOneModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOneModel) ProtoMessage() {}

func (x *DeleteOneModel) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_write_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOneModel.ProtoReflect.Descriptor instead.
func (*DeleteOneModel) Descriptor() ([]byte, []int) {
	return file_bulk_write_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteOneModel) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *DeleteOneModel) GetHint() []byte {
	if x != nil {
		return x.Hint
	}
	return nil
}

type DeleteManyModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter []byte `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Hint   []byte `protobuf:"bytes,2,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *DeleteManyModel) Reset() {
	*x = DeleteManyModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bulk_write_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteManyModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManyModel) ProtoMessage() {}

func (x *DeleteManyModel) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_write_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManyModel.ProtoReflect.Descriptor instead.
func (*DeleteManyModel) Descriptor() ([]byte, []int) {
	return file_bulk_write_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteManyModel) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *DeleteManyModel) GetHint() []byte {
	if x != nil {
		return x.Hint
	}
	return nil
}

type ReplaceOneModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Upsert      *wrapperspb.BoolValue `protobuf:"bytes,1,opt,name=upsert,proto3" json:"upsert,omitempty"`
	Filter      []byte                `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Replacement []byte                `protobuf:"bytes,3,opt,name=replacement,proto3" json:"replacement,omitempty"`
	Hint        []byte                `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *ReplaceOneModel) Reset() {
	*x = ReplaceOneModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bulk_write_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplaceOneModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceOneModel) ProtoMessage() {}

func (x *ReplaceOneModel) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_write_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceOneModel.ProtoReflect.Descriptor instead.
func (*ReplaceOneModel) Descriptor() ([]byte, []int) {
	return file_bulk_write_proto_rawDescGZIP(), []int{6}
}

func (x *ReplaceOneModel) GetUpsert() *wrapperspb.BoolValue {
	if x != nil {
		return x.Upsert
	}
	return nil
}

func (x *ReplaceOneModel) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ReplaceOneModel) GetReplacement() []byte {
	if x != nil {
		return x.Replacement
	}
	return nil
}

func (x *ReplaceOneModel) GetHint() []byte {
	if x != nil {
		return x.Hint
	}
	return nil
}

type UpdateOneModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Upsert *wrapperspb.BoolValue `protobuf:"bytes,1,opt,name=upsert,proto3" json:"upsert,omitempty"`
	Filter []byte                `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Update []byte                `protobuf:"bytes,3,opt,name=update,proto3" json:"update,omitempty"`
	Hint   []byte                `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *UpdateOneModel) Reset() {
	*x = UpdateOneModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bulk_write_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOneModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOneModel) ProtoMessage() {}

func (x *UpdateOneModel) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_write_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOneModel.ProtoReflect.Descriptor instead.
func (*UpdateOneModel) Descriptor() ([]byte, []int) {
	return file_bulk_write_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOneModel) GetUpsert() *wrapperspb.BoolValue {
	if x != nil {
		return x.Upsert
	}
	return nil
}

func (x *UpdateOneModel) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *UpdateOneModel) GetUpdate() []byte {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *UpdateOneModel) GetHint() []byte {
	if x != nil {
		return x.Hint
	}
	return nil
}

type UpdateManyModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Upsert *wrapperspb.BoolValue `protobuf:"bytes,1,opt,name=upsert,proto3" json:"upsert,omitempty"`
	Filter []byte                `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Update []byte                `protobuf:"bytes,3,opt,name=update,proto3" json:"update,omitempty"`
	Hint   []byte                `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *UpdateManyModel) Reset() {
	*x = UpdateManyModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bulk_write_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateManyModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManyModel) ProtoMessage() {}

func (x *UpdateManyModel) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_write_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManyModel.ProtoReflect.Descriptor instead.
func (*UpdateManyModel) Descriptor() ([]byte, []int) {
	return file_bulk_write_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateManyModel) GetUpsert() *wrapperspb.BoolValue {
	if x != nil {
		return x.Upsert
	}
	return nil
}

func (x *UpdateManyModel) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *UpdateManyModel) GetUpdate() []byte {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *UpdateManyModel) GetHint() []byte {
	if x != nil {
		return x.Hint
	}
	return nil
}

type BulkWriteResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InsertedCount int64            `protobuf:"varint,1,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"`
	MatchedCount  int64            `protobuf:"varint,2,opt,name=matched_count,json=matchedCount,proto3" json:"matched_count,omitempty"`
	ModifiedCount int64            `protobuf:"varint,3,opt,name=modified_count,json=modifiedCount,proto3" json:"modified_count,omitempty"`
	DeletedCount  int64            `protobuf:"varint,4,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	UpsertedCount int64            `protobuf:"varint,5,opt,name=upserted_count,json=upsertedCount,proto3" json:"upserted_count,omitempty"`
	UpsertedIds   map[int64][]byte `protobuf:"bytes,6,rep,name=upserted_ids,json=upsertedIds,proto3" json:"upserted_ids,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BulkWriteResult) Reset() {
	*x = BulkWriteResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bulk_write_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkWriteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkWriteResult) ProtoMessage() {}

func (x *BulkWriteResult) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_write_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkWriteResult.ProtoReflect.Descriptor instead.
func (*BulkWriteResult) Descriptor() ([]byte, []int) {
	return file_bulk_write_proto_rawDescGZIP(), []int{9}
}

func (x *BulkWriteResult) GetInsertedCount() int64 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

func (x *BulkWriteResult) GetMatchedCount() int64 {
	if x != nil {
		return x.MatchedCount
	}
	return 0
}

func (x *BulkWriteResult) GetModifiedCount() int64 {
	if x != nil {
		return x.ModifiedCount
	}
	return 0
}

func (x *BulkWriteResult) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *BulkWriteResult) GetUpsertedCount() int64 {
	if x != nil {
		return x.UpsertedCount
	}
	return 0
}

func (x *BulkWriteResult) GetUpsertedIds() map[int64][]byte {
	if x != nil {
		return x.UpsertedIds
	}
	return nil
}

var File_bulk_write_proto protoreflect.FileDescriptor

var file_bulk_write_proto_rawDesc = []byte{
	0x0a, 0x10, 0x62, 0x75, 0x6c, 0x6b, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xbe, 0x01, 0x0a, 0x10, 0x42, 0x75, 0x6c, 0x6b, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x69, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x69, 0x64, 0x12, 0x2d, 0x0a,
	0x0b, 0x77, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52,
	0x0b, 0x77, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x2d, 0x0a, 0x07,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x42, 0x75, 0x6c, 0x6b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x48, 0x00, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x6f,
	0x70, 0x74, 0x73, 0x22, 0xce, 0x01, 0x0a, 0x10, 0x42, 0x75, 0x6c, 0x6b, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x58, 0x0a, 0x1a, 0x62, 0x79, 0x70, 0x61,
	0x73, 0x73, 0x5f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42,
	0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x18, 0x62, 0x79, 0x70, 0x61, 0x73, 0x73,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x6c, 0x65, 0x74, 0x22, 0xfe, 0x02, 0x0a, 0x0a, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x39, 0x0a, 0x0e, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4f, 0x6e, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x4f, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x0e,
	0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4f, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x39,
	0x0a, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f,
	0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4f, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x3c, 0x0a, 0x0f, 0x72, 0x65, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x4f, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x4f, 0x6e, 0x65, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x4f,
	0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x39, 0x0a, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x48, 0x00, 0x52, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x6e, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x3c, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x48, 0x00, 0x52,
	0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x3c, 0x0a, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x0f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x05,
	0x0a, 0x03, 0x6f, 0x70, 0x73, 0x22, 0x2c, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4f,
	0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x22, 0x3c, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x6e, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x69, 0x6e,
	0x74, 0x22, 0x3d, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x69, 0x6e, 0x74,
	0x22, 0x93, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x4f, 0x6e, 0x65, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x12, 0x32, 0x0a, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x32, 0x0a, 0x06, 0x75, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x69, 0x6e,
	0x74, 0x22, 0x89, 0x01, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x32, 0x0a, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x22, 0xd6, 0x02,
	0x0a, 0x0f, 0x42, 0x75, 0x6c, 0x6b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x69, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a,
	0x0e, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x75, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x44, 0x0a, 0x0c, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x42, 0x75, 0x6c, 0x6b, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x65,
	0x64, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x75, 0x70, 0x73, 0x65, 0x72,
	0x74, 0x65, 0x64, 0x49, 0x64, 0x73, 0x1a, 0x3e, 0x0a, 0x10, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x65, 0x64, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x6d, 0x6f, 0x6e, 0x67,
	0x6f, 0x5f, 0x73, 0x74, 0x75, 0x62, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bulk_write_proto_rawDescOnce sync.Once
	file_bulk_write_proto_rawDescData = file_bulk_write_proto_rawDesc
)

func file_bulk_write_proto_rawDescGZIP() []byte {
	file_bulk_write_proto_rawDescOnce.Do(func() {
		file_bulk_write_proto_rawDescData = protoimpl.X.CompressGZIP(file_bulk_write_proto_rawDescData)
	})
	return file_bulk_write_proto_rawDescData
}

var file_bulk_write_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_bulk_write_proto_goTypes = []interface{}{
	(*BulkWriteRequest)(nil),     // 0: BulkWriteRequest
	(*BulkWriteOptions)(nil),     // 1: BulkWriteOptions
	(*WriteModel)(nil),           // 2: WriteModel
	(*InsertOneModel)(nil),       // 3: InsertOneModel
	(*DeleteOneModel)(nil),       // 4: DeleteOneModel
	(*DeleteManyModel)(nil),      // 5: DeleteManyModel
	(*ReplaceOneModel)(nil),      // 6: ReplaceOneModel
	(*UpdateOneModel)(nil),       // 7: UpdateOneModel
	(*UpdateManyModel)(nil),      // 8: UpdateManyModel
	(*BulkWriteResult)(nil),      // 9: BulkWriteResult
	nil,                          // 10: BulkWriteResult.UpsertedIdsEntry
	(*wrapperspb.BoolValue)(nil), // 11: google.protobuf.BoolValue
}
var file_bulk_write_proto_depIdxs = []int32{
	2,  // 0: BulkWriteRequest.writeModels:type_name -> WriteModel
	1,  // 1: BulkWriteRequest.options:type_name -> BulkWriteOptions
	11, // 2: BulkWriteOptions.bypass_document_validation:type_name -> google.protobuf.BoolValue
	11, // 3: BulkWriteOptions.ordered:type_name -> google.protobuf.BoolValue
	3,  // 4: WriteModel.insertOneModel:type_name -> InsertOneModel
	4,  // 5: WriteModel.deleteOneModel:type_name -> DeleteOneModel
	6,  // 6: WriteModel.replaceOneModel:type_name -> ReplaceOneModel
	7,  // 7: WriteModel.updateOneModel:type_name -> UpdateOneModel
	5,  // 8: WriteModel.deleteManyModel:type_name -> DeleteManyModel
	8,  // 9: WriteModel.updateManyModel:type_name -> UpdateManyModel
	11, // 10: ReplaceOneModel.upsert:type_name -> google.protobuf.BoolValue
	11, // 11: UpdateOneModel.upsert:type_name -> google.protobuf.BoolValue
	11, // 12: UpdateManyModel.upsert:type_name -> google.protobuf.BoolValue
	10, // 13: BulkWriteResult.upserted_ids:type_name -> BulkWriteResult.UpsertedIdsEntry
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_bulk_write_proto_init() }
func file_bulk_write_proto_init() {
	if File_bulk_write_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bulk_write_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkWriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bulk_write_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkWriteOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bulk_write_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bulk_write_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertOneModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bulk_write_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOneModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bulk_write_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteManyModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bulk_write_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplaceOneModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bulk_write_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOneModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bulk_write_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateManyModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bulk_write_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkWriteResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bulk_write_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*BulkWriteRequest_Options)(nil),
	}
	file_bulk_write_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*WriteModel_InsertOneModel)(nil),
		(*WriteModel_DeleteOneModel)(nil),
		(*WriteModel_ReplaceOneModel)(nil),
		(*WriteModel_UpdateOneModel)(nil),
		(*WriteModel_DeleteManyModel)(nil),
		(*WriteModel_UpdateManyModel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bulk_write_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bulk_write_proto_goTypes,
		DependencyIndexes: file_bulk_write_proto_depIdxs,
		MessageInfos:      file_bulk_write_proto_msgTypes,
	}.Build()
	File_bulk_write_proto = out.File
	file_bulk_write_proto_rawDesc = nil
	file_bulk_write_proto_goTypes = nil
	file_bulk_write_proto_depIdxs = nil
}
