name: proto_generator_test
description: A starting point for Dart libraries or applications.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  proto_generator:
    path: ../proto_generator
  # decimal: ^2.0.0
  # fixnum: ^1.0.0
  # grpc: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.4
  build_verify: ^3.0.0
  lints: ^2.0.0
  test: ^1.17.0

dependency_overrides:
  proto_annotations:
    path: ../proto_annotations
  squarealfa_generators_common:
    path: ../../generators_common
  squarealfa_common_types:
    path: ../../common_types
  proto_generator:
    path: ../../proto_mapper/proto_generator
