// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: model.proto

package stubs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GPerson struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldsOfSuperClass *GAnimal                `protobuf:"bytes,1,opt,name=fieldsOfSuperClass,proto3" json:"fieldsOfSuperClass,omitempty"`
	Name               string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *GPerson) Reset() {
	*x = GPerson{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPerson) ProtoMessage() {}

func (x *GPerson) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPerson.ProtoReflect.Descriptor instead.
func (*GPerson) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *GPerson) GetFieldsOfSuperClass() *GAnimal {
	if x != nil {
		return x.FieldsOfSuperClass
	}
	return nil
}

func (x *GPerson) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPerson) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

type GListOfPerson struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GPerson `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GListOfPerson) Reset() {
	*x = GListOfPerson{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GListOfPerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GListOfPerson) ProtoMessage() {}

func (x *GListOfPerson) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GListOfPerson.ProtoReflect.Descriptor instead.
func (*GListOfPerson) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *GListOfPerson) GetItems() []*GPerson {
	if x != nil {
		return x.Items
	}
	return nil
}

type GAnimal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldsOfSuperClass *GFieldsOfBeing `protobuf:"bytes,1,opt,name=fieldsOfSuperClass,proto3" json:"fieldsOfSuperClass,omitempty"`
	Height             int32           `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GAnimal) Reset() {
	*x = GAnimal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GAnimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GAnimal) ProtoMessage() {}

func (x *GAnimal) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GAnimal.ProtoReflect.Descriptor instead.
func (*GAnimal) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2}
}

func (x *GAnimal) GetFieldsOfSuperClass() *GFieldsOfBeing {
	if x != nil {
		return x.FieldsOfSuperClass
	}
	return nil
}

func (x *GAnimal) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GListOfAnimal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GAnimal `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GListOfAnimal) Reset() {
	*x = GListOfAnimal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GListOfAnimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GListOfAnimal) ProtoMessage() {}

func (x *GListOfAnimal) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GListOfAnimal.ProtoReflect.Descriptor instead.
func (*GListOfAnimal) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{3}
}

func (x *GListOfAnimal) GetItems() []*GAnimal {
	if x != nil {
		return x.Items
	}
	return nil
}

type GFieldsOfBeing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mass float64 `protobuf:"fixed64,2,opt,name=mass,proto3" json:"mass,omitempty"`
}

func (x *GFieldsOfBeing) Reset() {
	*x = GFieldsOfBeing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GFieldsOfBeing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GFieldsOfBeing) ProtoMessage() {}

func (x *GFieldsOfBeing) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GFieldsOfBeing.ProtoReflect.Descriptor instead.
func (*GFieldsOfBeing) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{4}
}

func (x *GFieldsOfBeing) GetMass() float64 {
	if x != nil {
		return x.Mass
	}
	return 0
}

type GBeing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Props:
	//
	//	*GBeing_Being
	//	*GBeing_Animal
	Props isGBeing_Props `protobuf_oneof:"props"`
}

func (x *GBeing) Reset() {
	*x = GBeing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GBeing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GBeing) ProtoMessage() {}

func (x *GBeing) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GBeing.ProtoReflect.Descriptor instead.
func (*GBeing) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{5}
}

func (m *GBeing) GetProps() isGBeing_Props {
	if m != nil {
		return m.Props
	}
	return nil
}

func (x *GBeing) GetBeing() *GFieldsOfBeing {
	if x, ok := x.GetProps().(*GBeing_Being); ok {
		return x.Being
	}
	return nil
}

func (x *GBeing) GetAnimal() *GAnimal {
	if x, ok := x.GetProps().(*GBeing_Animal); ok {
		return x.Animal
	}
	return nil
}

type isGBeing_Props interface {
	isGBeing_Props()
}

type GBeing_Being struct {
	Being *GFieldsOfBeing `protobuf:"bytes,1,opt,name=being,proto3,oneof"`
}

type GBeing_Animal struct {
	Animal *GAnimal `protobuf:"bytes,2,opt,name=animal,proto3,oneof"`
}

func (*GBeing_Being) isGBeing_Props() {}

func (*GBeing_Animal) isGBeing_Props() {}

type GListOfBeing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GBeing `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GListOfBeing) Reset() {
	*x = GListOfBeing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GListOfBeing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GListOfBeing) ProtoMessage() {}

func (x *GListOfBeing) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GListOfBeing.ProtoReflect.Descriptor instead.
func (*GListOfBeing) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{6}
}

func (x *GListOfBeing) GetItems() []*GBeing {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_model_proto protoreflect.FileDescriptor

var file_model_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x73,
	0x71, 0x75, 0x61, 0x72, 0x65, 0x61, 0x6c, 0x66, 0x61, 0x2e, 0x6e, 0x6f, 0x7a, 0x61, 0x72, 0x64,
	0x2e, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x6f, 0x67, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x07, 0x47, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x12, 0x52, 0x0a, 0x12, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x4f, 0x66,
	0x53, 0x75, 0x70, 0x65, 0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x61, 0x6c, 0x66, 0x61, 0x2e, 0x6e, 0x6f,
	0x7a, 0x61, 0x72, 0x64, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x41, 0x6e,
	0x69, 0x6d, 0x61, 0x6c, 0x52, 0x12, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x4f, 0x66, 0x53, 0x75,
	0x70, 0x65, 0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x49, 0x0a, 0x0d,
	0x47, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x38, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73,
	0x71, 0x75, 0x61, 0x72, 0x65, 0x61, 0x6c, 0x66, 0x61, 0x2e, 0x6e, 0x6f, 0x7a, 0x61, 0x72, 0x64,
	0x2e, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x7c, 0x0a, 0x07, 0x47, 0x41, 0x6e, 0x69, 0x6d,
	0x61, 0x6c, 0x12, 0x59, 0x0a, 0x12, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x4f, 0x66, 0x53, 0x75,
	0x70, 0x65, 0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29,
	0x2e, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x61, 0x6c, 0x66, 0x61, 0x2e, 0x6e, 0x6f, 0x7a, 0x61,
	0x72, 0x64, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x4f, 0x66, 0x42, 0x65, 0x69, 0x6e, 0x67, 0x52, 0x12, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x4f, 0x66, 0x53, 0x75, 0x70, 0x65, 0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x49, 0x0a, 0x0d, 0x47, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66,
	0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x38, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x61, 0x6c,
	0x66, 0x61, 0x2e, 0x6e, 0x6f, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x6f,
	0x67, 0x2e, 0x47, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0x24, 0x0a, 0x0e, 0x47, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x4f, 0x66, 0x42, 0x65, 0x69,
	0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x6d, 0x61, 0x73, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x06, 0x47, 0x42, 0x65, 0x69, 0x6e,
	0x67, 0x12, 0x41, 0x0a, 0x05, 0x62, 0x65, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x61, 0x6c, 0x66, 0x61, 0x2e, 0x6e, 0x6f,
	0x7a, 0x61, 0x72, 0x64, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x4f, 0x66, 0x42, 0x65, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x05, 0x62,
	0x65, 0x69, 0x6e, 0x67, 0x12, 0x3c, 0x0a, 0x06, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x61, 0x6c, 0x66,
	0x61, 0x2e, 0x6e, 0x6f, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x6f, 0x67,
	0x2e, 0x47, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x06, 0x61, 0x6e, 0x69, 0x6d,
	0x61, 0x6c, 0x42, 0x07, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x22, 0x47, 0x0a, 0x0c, 0x47,
	0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x42, 0x65, 0x69, 0x6e, 0x67, 0x12, 0x37, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x71, 0x75,
	0x61, 0x72, 0x65, 0x61, 0x6c, 0x66, 0x61, 0x2e, 0x6e, 0x6f, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x74,
	0x65, 0x63, 0x68, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x42, 0x65, 0x69, 0x6e, 0x67, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x73, 0x74, 0x75, 0x62, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData = file_model_proto_rawDesc
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_proto_rawDescData)
	})
	return file_model_proto_rawDescData
}

var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_model_proto_goTypes = []interface{}{
	(*GPerson)(nil),                // 0: squarealfa.nozard.techlog.GPerson
	(*GListOfPerson)(nil),          // 1: squarealfa.nozard.techlog.GListOfPerson
	(*GAnimal)(nil),                // 2: squarealfa.nozard.techlog.GAnimal
	(*GListOfAnimal)(nil),          // 3: squarealfa.nozard.techlog.GListOfAnimal
	(*GFieldsOfBeing)(nil),         // 4: squarealfa.nozard.techlog.GFieldsOfBeing
	(*GBeing)(nil),                 // 5: squarealfa.nozard.techlog.GBeing
	(*GListOfBeing)(nil),           // 6: squarealfa.nozard.techlog.GListOfBeing
	(*wrapperspb.StringValue)(nil), // 7: google.protobuf.StringValue
}
var file_model_proto_depIdxs = []int32{
	2, // 0: squarealfa.nozard.techlog.GPerson.fieldsOfSuperClass:type_name -> squarealfa.nozard.techlog.GAnimal
	7, // 1: squarealfa.nozard.techlog.GPerson.description:type_name -> google.protobuf.StringValue
	0, // 2: squarealfa.nozard.techlog.GListOfPerson.items:type_name -> squarealfa.nozard.techlog.GPerson
	4, // 3: squarealfa.nozard.techlog.GAnimal.fieldsOfSuperClass:type_name -> squarealfa.nozard.techlog.GFieldsOfBeing
	2, // 4: squarealfa.nozard.techlog.GListOfAnimal.items:type_name -> squarealfa.nozard.techlog.GAnimal
	4, // 5: squarealfa.nozard.techlog.GBeing.being:type_name -> squarealfa.nozard.techlog.GFieldsOfBeing
	2, // 6: squarealfa.nozard.techlog.GBeing.animal:type_name -> squarealfa.nozard.techlog.GAnimal
	5, // 7: squarealfa.nozard.techlog.GListOfBeing.items:type_name -> squarealfa.nozard.techlog.GBeing
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPerson); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GListOfPerson); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GAnimal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GListOfAnimal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GFieldsOfBeing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GBeing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GListOfBeing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_model_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*GBeing_Being)(nil),
		(*GBeing_Animal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_rawDesc = nil
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
