name: squarealfa_entity_adapter
description: Provides the annotations and a facade to several SquareAlfa
  framework services that are required to expose PODOs via gRPC services
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/entity_adapter/entity_adapter
repository: https://gitlab.com/squarealfa/dart_framework/

version: 3.1.5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  defaults_provider_annotations: ^2.1.0
  map_mapper_annotations: ^3.1.1
  proto_annotations: ^2.1.0
  squarealfa_entity_annotations: ^2.1.0
  squarealfa_common_types: ^1.1.0
  grpc: ^3.0.0

dev_dependencies:
  lints: ^2.0.0

