name: squarealfa_entity_adapter
description: Provides the annotations and a facade to several SquareAlfa
  framework services that are required to expose PODOs via gRPC services
homepage: https://github.com/squarealfa/dart_framework/tree/main/entity_adapter/entity_adapter
repository: https://github.com/squarealfa/dart_framework/

version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none

dependencies:
  defaults_provider_annotations:
    path: ../../defaults_provider/defaults_provider_annotations
  map_mapper_annotations:
    path: ../../map_mapper/map_mapper_annotations
  proto_annotations:
    path: ../../proto_mapper/proto_annotations
  squarealfa_entity_annotations:
    path: ../../entity/entity_annotations
  grpc: ^3.0.0

dev_dependencies:
  lints: ^1.0.1
