name: defaults_provider_generator
description: Generates business class Defaults Providers, that provide default values for non-nullable PODO properties
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/defaults_provider/defaults_provider_generator
repository: https://gitlab.com/dartaculous/dartaculous
version: 2.4.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  source_gen: ^1.2.1
  defaults_provider_annotations: ^2.1.0
  squarealfa_generators_common: ^2.10.0
  build: ^2.0.0
  decimal: ^2.1.0
  analyzer: ^5.1.0
  


dev_dependencies:
  lints: ^2.0.0

