name: firebase_go_admin
description: Firebase Administration based on the official Firebase Admin GO SDK via Dart FFI.
repository: https://gitlab.com/dartaculous/dartaculous
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/firebase_admin
version: 0.11.2-dev.7


environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies: 
  args: ^2.3.0
  ffi: ^2.0.1
  path: ^1.8.0
  proto_annotations: ^3.0.0-dev.7
  protobuf: ^2.1.0
  tuple: ^2.0.0
  go_bridge: ^1.4.1
  fixnum: ^1.0.1

dev_dependencies:
  ffigen: ^7.2.0
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
  proto_generator: ^4.0.0-dev.16
platforms:
  linux:
  windows:
  macos:

ffigen:
  name: LibFirebaseAdmin
  description: Go Firebase Admin SDK
  output: 'lib/src/lib_firebase_admin.dart'
  headers:
    entry-points:
      - go/firebase_go_admin.h

