# targets:
#   $default:
#     builders:
#       proto_generator:proto_mapper_generator:
#         options:
#           prefix: G # or '' for no prefix
#           dateTimePrecision: microseconds
#           generateProtoMapper: false
#           generateMapMapper: false


#       proto_generator:proto_generator:
#         options:
#           prefix: G # or '' for no prefix
#           useProtoFieldNamingConventions: true
#           package: mentoralfa
      
