name: example
description: Example for squarealfa_validation_generator
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  decimal: ^2.1.0
  fixnum: ^1.0.0
  squarealfa_entity_adapter: ^3.0.5

dev_dependencies:
  
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  lints: ^1.0.1
  squarealfa_entity_adapter_generator: ^3.0.5
  test: ^1.17.0

dependency_overrides:
  squarealfa_entity_adapter:
    path: ../entity_adapter