name: arango_driver
description: ArangoDB driver, working on top of ArangoDB HTTP API. This package is a fork of the dart_arango_min package.
repository: https://gitlab.com/squarealfa/dart_framework
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/arango_driver
version: 3.3.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.1
