name: arango_driver
description: ArangoDB driver, working on top of ArangoDB HTTP API. This package is a fork of the dart_arango_min package.
repository: https://gitlab.com/dartaculous/dartaculous
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/arango_driver
version: 4.0.0-dev.2

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  test: ^1.20.1
  lints: ^2.0.0
