name: synced_data
description: Contains classes meant to be used by the dbsync package on both
  client and server
repository: https://gitlab.com/dartaculous/dartaculous
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/dbsync/synced_data
version: 0.0.1-dev.1

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
