name: mongo_go
description: Provides a MongoDB driver based on the official GO SDK via Dart FFI meant to be used in Dart server-side code.
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/mongo_go
repository: https://gitlab.com/squarealfa/dart_framework
version: 5.1.3-dev.0


environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  args: ^2.3.0
  ffi: ^2.0.1
  path: ^1.8.0
  proto_annotations: ^3.0.0-dev.0
  protobuf: ^2.1.0
  tuple: ^2.0.0
  go_bridge: ^1.3.0
  meta: ^1.8.0
  fixnum: ^1.0.1
  decimal: ^2.3.0
  bson: ^3.0.0
  pubspec: ^2.3.0
  
dev_dependencies:
  ffigen: ^7.2.0
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
  proto_generator: ^4.0.0-dev.0
platforms:
  linux:
  windows:
  macos:

ffigen:
  name: LibMongoProxy
  description: MongoProxy GO driver
  output: 'lib/src/lib_mongo_go.dart'
  headers:
    entry-points:
      - go/mongo_go.h
