name: mongo_go
description: MongoDB driver based on the official GO SDK via Dart FFI.
version: 0.0.1

publish_to: none

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies: 
  args: ^2.3.0
  ffi: ^2.0.1
  path: ^1.8.0
  proto_annotations: ^2.1.1
  protobuf: ^2.1.0
  tuple: ^2.0.0
  go_bridge:
    path: ../go_bridge
  bson: ^2.0.1
  meta: ^1.8.0
  
dev_dependencies:
  ffigen: ^6.1.2
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
  proto_generator: ^3.3.4


ffigen:
  name: LibMongoProxy
  description: MongoProxy GO driver
  output: 'lib/src/lib_mongo_proxy.dart'
  headers:
    entry-points:
      - ../go/mongo_proxy/out/mongo_proxy.h

