build: .PHONY
	cd general && make build
	cd json && make build
	cd mongo && make build

test: .PHONY
	cd general && make test
	cd json && make test
	cd mongo && make test

_test: .PHONY
	cd general && make _test
	cd json && make _test
	cd mongo && make _test

clean: .PHONY
	cd general && make clean
	cd json && make clean
	cd mongo && make clean

.PHONY:
