name: dbsync
description: Contains algorithm to perform synchronization between Sqlite database and server API
repository: https://gitlab.com/dartaculous/dartaculous
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/dbsync/dbsync
version: 0.1.0-dev.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.8.0
  grpc: ^3.1.0
  logging: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0