name: squarealfa_common_types
description: Common types to be used by SquareAlfa Dart Framework.
homepage: https://github.com/squarealfa/dart_framework/tree/main/common_types
repository: https://github.com/squarealfa/dart_framework
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
