name: mongo_mapper
description: 
  Contains annotations and mappers to allow the mapping between PODOs and Map<String, dynamic> maps 
  used to interact with MongoDB
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/map_mapper/mongo_mapper
repository: https://gitlab.com/squarealfa/dart_framework
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  squarealfa_common_types: ^1.2.0
  map_mapper_annotations: ^3.2.1
  bson: ^3.0.1

dev_dependencies:
  lints: ^2.0.0
