// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: fcm/change_notification.proto

package fcm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tokens   []string `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Key      string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	TypeName string   `protobuf:"bytes,3,opt,name=typeName,proto3" json:"typeName,omitempty"`
	Rev      string   `protobuf:"bytes,4,opt,name=rev,proto3" json:"rev,omitempty"`
	HashCode string   `protobuf:"bytes,5,opt,name=hashCode,proto3" json:"hashCode,omitempty"`
}

func (x *ChangeNotification) Reset() {
	*x = ChangeNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fcm_change_notification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeNotification) ProtoMessage() {}

func (x *ChangeNotification) ProtoReflect() protoreflect.Message {
	mi := &file_fcm_change_notification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeNotification.ProtoReflect.Descriptor instead.
func (*ChangeNotification) Descriptor() ([]byte, []int) {
	return file_fcm_change_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeNotification) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ChangeNotification) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ChangeNotification) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *ChangeNotification) GetRev() string {
	if x != nil {
		return x.Rev
	}
	return ""
}

func (x *ChangeNotification) GetHashCode() string {
	if x != nil {
		return x.HashCode
	}
	return ""
}

var File_fcm_change_notification_proto protoreflect.FileDescriptor

var file_fcm_change_notification_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x66, 0x63, 0x6d, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x88, 0x01, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x65, 0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x76, 0x12, 0x1a,
	0x0a, 0x08, 0x68, 0x61, 0x73, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x68, 0x61, 0x73, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f,
	0x73, 0x74, 0x75, 0x62, 0x73, 0x2f, 0x66, 0x63, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_fcm_change_notification_proto_rawDescOnce sync.Once
	file_fcm_change_notification_proto_rawDescData = file_fcm_change_notification_proto_rawDesc
)

func file_fcm_change_notification_proto_rawDescGZIP() []byte {
	file_fcm_change_notification_proto_rawDescOnce.Do(func() {
		file_fcm_change_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_fcm_change_notification_proto_rawDescData)
	})
	return file_fcm_change_notification_proto_rawDescData
}

var file_fcm_change_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fcm_change_notification_proto_goTypes = []interface{}{
	(*ChangeNotification)(nil), // 0: ChangeNotification
}
var file_fcm_change_notification_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fcm_change_notification_proto_init() }
func file_fcm_change_notification_proto_init() {
	if File_fcm_change_notification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fcm_change_notification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fcm_change_notification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fcm_change_notification_proto_goTypes,
		DependencyIndexes: file_fcm_change_notification_proto_depIdxs,
		MessageInfos:      file_fcm_change_notification_proto_msgTypes,
	}.Build()
	File_fcm_change_notification_proto = out.File
	file_fcm_change_notification_proto_rawDesc = nil
	file_fcm_change_notification_proto_goTypes = nil
	file_fcm_change_notification_proto_depIdxs = nil
}
