name: defaults_provider_annotations
description:
  Contains annotations to drive the code generator that creates defaults providers.
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/defaults_provider/defaults_provider_annotations
repository: https://gitlab.com/dartaculous/dartaculous
version: 3.0.0


environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
