name: sembast_sync
description: Adapter for dbsync that uses sqlite database.
repository: https://gitlab.com/dartaculous/dartaculous
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/dbsync/sembast_sync
version: 0.0.1-dev.4

environment:
  sdk: '>=2.19.4 <3.0.0'

publish_to: none

dependencies:
  sembast:  ^3.4.3+1
  meta: ^1.8.0
  dbsync: #^0.0.1-dev.16
    path: ../dbsync

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  
