name: firebase_auth_admin
description: Firebase Authorization Administration based on the official Firebase Admin GO SDK via Dart FFI.
repository: https://gitlab.com/dartaculous/dartaculous
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/firebase-auth-admin
version: 0.9.7


environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies: 
  args: ^2.3.0
  ffi: ^1.1.2
  path: ^1.8.0
  proto_annotations: ^2.1.1


dev_dependencies:
  ffigen: ^4.1.0
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
  proto_generator: ^3.3.4

executables: 
  firebase-auth: firebase_auth_admin

ffigen:
  name: LibAuth
  description: Go Firebase Auth SDK
  output: 'lib/src/lib_auth.dart'
  headers:
    entry-points:
      - go/lib-auth.h

