name: proto_generator
description: Code generation of .proto and Dart mapper classes to facilitate the usage of PODOs (plain-old-dart-objects) with gRPC
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/proto_mapper/proto_generator
repository: https://gitlab.com/squarealfa/dart_framework
version: 3.3.7

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  source_gen: ^1.2.1
  proto_annotations: ^2.1.1
  decimal: ^2.0.0
  grpc: ^3.0.2
  analyzer: ^4.7.0
  build: ^2.0.0
  recase: ^4.0.0
  squarealfa_common_types: ^1.1.0
  squarealfa_generators_common: ^2.4.3
dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.0
