name: defaults_provider_test
description: A starting point for Dart libraries or applications.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  defaults_provider_generator:
    path: ../defaults_provider_generator
  fixnum: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  lints: ^2.0.0
  test: ^1.17.12
  

dependency_overrides:
  squarealfa_generators_common:
    path: ../../generators_common
