# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:

  csharpBuilder:
    import: "package:csharp_generator/csharp_generator.dart"
    builder_factories: ['csharpBuilder']
    build_extensions: 
      $lib$: 
        - .cs
      .dart:
        - proto_map.g.part
    build_to: source
    auto_apply: root_package
#    applies_builders: ["source_gen:combining_builder", "proto_generator:protoFromCache"]


#  protoFromCache:
#    import: "package:proto_generator/proto_generator.dart"
#    builder_factories: ['protoFromCache']
#    build_extensions: {".tproto": [".proto"]}
#    required_inputs: [".tproto"]
#    build_to: source
#    auto_apply: none
