name: csharp_generator
description: Code generation of C# classes based on Dart classes
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/charp_mapper/csharp_generator
repository: https://gitlab.com/dartaculous/dartaculous
version: 0.0.1-dev.7

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  source_gen: ^1.2.1
  csharp_annotations: ^0.0.1-dev.0
  decimal: ^2.0.0
  grpc: ^3.0.2
  analyzer: ^5.2.0
  build: ^2.0.0
  recase: ^4.0.0
  glob: ^2.1.1
  path: ^1.8.2
  tuple: ^2.0.1
  squarealfa_generators_common: ^3.0.0-dev.2
  squarealfa_entity_annotations: ^3.0.0-dev.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.0
