# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:

  validation_generator:
    import: "package:squarealfa_entity_generator/squarealfa_entity_generator.dart"
    builder_factories: ["validationGeneratorBuilder"]
    build_extensions: {".dart": ["validation.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  builder_generator:
    import: "package:squarealfa_entity_generator/squarealfa_entity_generator.dart"
    builder_factories: ["builderBuilder"]
    build_extensions: {".dart": ["builder.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  copywith_generator:
    import: "package:squarealfa_entity_generator/squarealfa_entity_generator.dart"
    builder_factories: ["copyWithBuilder"]
    build_extensions: {".dart": ["copywith.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  crud_permissions_generator:
    import: "package:squarealfa_entity_generator/squarealfa_entity_generator.dart"
    builder_factories: ["crudPermissionsBuilder"]
    build_extensions: {".dart": ["crud_permissions.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  defaults_provider_generator:
    import: "package:squarealfa_entity_generator/squarealfa_entity_generator.dart"
    builder_factories: ["defaultsProviderGeneratorBuilder"]
    build_extensions: {".dart": ["defaults_provider.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
