name: arangodb_repository
description: Concrete implementation of the nosql_repository package for the ArangoDB database.
repository: https://gitlab.com/dartaculous/dartaculous
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/arango_repository
version: 6.0.2

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  arango_driver: ^3.6.1
  nosql_repository: ^5.0.2
  squarealfa_security: ^2.2.1
  tuple: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
