name: arangodb_repository
description: Concrete implementation of the nosql_repository package for the ArangoDB database.
repository: https://gitlab.com/squarealfa/dart_framework
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/arango_repository
version: 5.0.7

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  arango_driver: ^3.5.0
  nosql_repository: ^4.0.0
  squarealfa_security: ^2.0.0
  tuple: ^2.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.0
