name: ffi_lib
description: Tool to install native library associated to (non-Flutter) Dart package
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/tools/ffi_lib
repository: https://gitlab.com/squarealfa/dart_framework
version: 0.1.0-dev.2


environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  path: ^1.8.0
  pubspec: ^2.3.0

platforms:
  linux:

executables:
  ffi-lib: ffi_lib