name: squarealfa_entity_adapter_generator
description: Generates a facade to several SquareAlfa framework services that are required to expose PODOs via gRPC services.
homepage: https://github.com/squarealfa/dart_framework/tree/main/entity_adapter/entity_adapter_generator
repository: https://github.com/squarealfa/dart_framework/

version: 3.0.5


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  source_gen: ^1.2.1
  squarealfa_entity_adapter: ^3.0.5
  map_mapper_generator: ^3.0.3
  proto_generator: ^3.0.4
  defaults_provider_generator: ^2.0.1
  squarealfa_entity_generator: ^2.0.2
  squarealfa_generators_common: ^2.1.3
  squarealfa_common_types: ^1.0.1
  analyzer: ^3.0.0
  build: ^2.0.0


dev_dependencies:
  lints: ^1.0.1
  test: ^1.14.4


# dependency_overrides:
#   map_mapper_annotations:
#     path: ../../map_mapper/map_mapper_annotations
#   squarealfa_entity_adapter:
#     path: ../entity_adapter
