name: squarealfa_entity_adapter_generator
description: Generates a facade to several SquareAlfa framework services that are required to expose PODOs via gRPC services.
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/entity_adapter/entity_adapter_generator
repository: https://gitlab.com/squarealfa/dart_framework/

version: 3.2.6


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  source_gen: ^1.2.1
  squarealfa_entity_adapter: ^3.1.3
  map_mapper_generator: ^3.4.3
  proto_generator: ^3.3.7
  defaults_provider_generator: ^2.2.3
  squarealfa_entity_generator: ^2.1.8
  squarealfa_generators_common: ^2.4.3
  squarealfa_common_types: ^1.1.0
  analyzer: ^4.7.0
  build: ^2.0.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.14.4

