name: grpc_host
description: Hosts gRPC services
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/grpc_host
repository: https://gitlab.com/squarealfa/dart_framework
version: 3.3.0


environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  nosql_repository: ^2.0.0
  squarealfa_entity_adapter: ^3.1.0
  squarealfa_security: ^2.1.2
  grpc: ^3.0.0
  yaml: ^3.1.0
  kiwi: ^4.0.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.14.4

# dependency_overrides:
#   proto_generator:
#     path: ../proto_mapper/proto_generator
#   proto_annotations:
#     path: ../proto_mapper/proto_annotations
