name: grpc_host
description: Hosts gRPC services
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/grpc_host
repository: https://gitlab.com/squarealfa/dart_framework
version: 5.0.6-dev.2


environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  nosql_repository: ^6.0.0-dev.1
  squarealfa_security: ^3.0.0-dev.1
  grpc: ^3.0.0
  yaml: ^3.1.0
  kiwi: ^4.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.14.4
