name: cloud_run_grpc_auth
description: Identity for Google Cloud Run Services as gRPC clients
repository: https://gitlab.com/squarealfa/dart_framework
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/security/cloud_run_grpc_auth
version: 0.10.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.0
  cryptography: ^2.0.1
  jose: ^0.3.2
  http: ^0.13.3
  grpc: ^3.0.2
  googleapis_auth: ^1.3.0
  meta: ^1.7.0


dev_dependencies:
  test: ^1.17.11
  lints: ^1.0.1
