name: proto_annotations
description: Annotations to mark and configure business model classes for code
  generation of .proto and Dart mapper classes
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/proto_mapper/proto_annotations
repository: https://gitlab.com/squarealfa/dart_framework
version: 2.1.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fixnum: ^1.0.0
  grpc: ^3.0.2
  squarealfa_common_types: ^1.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.0



# dependency_overrides:
#   squarealfa_common_types:
#     path: ../../common_types