name: proto_annotations
description: Annotations to mark and configure business model classes for code
  generation of .proto and Dart mapper classes
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/proto_mapper/proto_annotations
repository: https://gitlab.com/dartaculous/dartaculous
version: 3.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  decimal: ^2.3.2
  fixnum: ^1.0.0
  grpc: ^3.0.2
  rational: ^2.2.2
  json_annotation: ^4.8.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4

