name: squarealfa_entity_annotations
description: Annotations and classes to drive code generation for validation and entity life cycle.
homepage: https://gitlab.com/dartaculous/dartaculous/-/tree/main/entity/entity_annotations
repository: https://gitlab.com/dartaculous/dartaculous
version: 4.0.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  
dependencies:
  decimal: ^2.0.0
