name: nosql_repository
description: Repository pattern oriented towards NoSQL databases. This package defines the interfaces to be used by an application to access a database, namely for CRUD and searching.
repository: https://github.com/squarealfa/dart_framework
homepage: https://github.com/squarealfa/dart_framework/tree/main/nosql_repository
version: 1.1.1

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none

dependencies:
  squarealfa_security:
    path: ../squarealfa_security

dev_dependencies:
  lints: ^1.0.1-nullsafety.3
  test: ^1.14.4
